project:
  type: website

website:
  title: "Bitcoin Price Trend Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: models.qmd
        text: Models
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



