<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Bitcoin Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-dfb324f25d9b1687192fa8be62ac8f9c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Bitcoin Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./models.html" aria-current="page"> 
<span class="menu-text">Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link active" data-scroll-target="#linear-regression">Linear Regression</a></li>
  <li><a href="#linear-regression-model" id="toc-linear-regression-model" class="nav-link" data-scroll-target="#linear-regression-model">Linear Regression Model</a>
  <ul class="collapse">
  <li><a href="#coefficient-by-coefficient-interpretation" id="toc-coefficient-by-coefficient-interpretation" class="nav-link" data-scroll-target="#coefficient-by-coefficient-interpretation">Coefficient-by-Coefficient Interpretation</a></li>
  </ul></li>
  <li><a href="#granger-causality" id="toc-granger-causality" class="nav-link" data-scroll-target="#granger-causality">Granger Causality</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Bitcoin Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="models_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<p>To analyze the relationship between macroeconomic indicators and Bitcoin price, a linear regression model was employed. This approach is appropriate because it allows us to quantify the individual effect of each predictor—such as CPI, interest rates, money supply (M2), and the stock market—on the response variable, Bitcoin price, while controlling for the influence of other variables. Linear regression is a widely used and interpretable statistical method for modeling continuous outcomes and identifying statistically significant predictors. By fitting the model, we were able to estimate coefficients for each macroeconomic factor, assess their significance using p-values, and construct confidence intervals to understand the precision of our estimates. The model helps determine which variables have meaningful associations with Bitcoin price and whether these relationships are positive or negative.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 7
  term         estimate std.error statistic  p.value conf.low conf.high
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)   0.0982     0.0696     1.41  1.59e- 1 -0.0384     0.235 
2 CPI           0.390      1.08       0.359 7.19e- 1 -1.74       2.52  
3 FedRate       0.00227    0.0218     0.104 9.17e- 1 -0.0406     0.0451
4 DXY          -0.783      0.282     -2.78  5.53e- 3 -1.34      -0.230 
5 M2            0.871      0.442      1.97  4.90e- 2  0.00393    1.74  
6 Unemployment  0.00469    0.0428     0.109 9.13e- 1 -0.0793     0.0887
7 gold          0.132      0.0871     1.51  1.30e- 1 -0.0389     0.303 
8 Treasury     -0.0962     0.0258    -3.73  1.95e- 4 -0.147     -0.0456
9 dow           1.01       0.0711    14.2   7.37e-44  0.873      1.15  </code></pre>
</div>
</div>
</section>
<section id="linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-model">Linear Regression Model</h2>
<p><span class="math display">\[\begin{align*}
\hat{\text{BTC}} =\ &amp;
\beta_0
+ \beta_1 \cdot \text{CPI} \quad (\beta_1 = 0.390) \\
&amp; + \beta_2 \cdot \text{FedRate} \quad (\beta_2 = 0.00227) \\
&amp; + \beta_3 \cdot \text{DXY} \quad (\beta_3 = -0.783) \\
&amp; + \beta_4 \cdot \text{M2} \quad (\beta_4 = 0.871) \\
&amp; + \beta_5 \cdot \text{Unemployment} \quad (\beta_5 = 0.00469) \\
&amp; + \beta_6 \cdot \text{Gold} \quad (\beta_6 = 0.132) \\
&amp; + \beta_7 \cdot \text{Treasury} \quad (\beta_7 = -0.0962) \\
&amp; + \beta_8 \cdot \text{Dow} \quad (\beta_8 = 1.01)
\end{align*}\]</span></p>
<section id="coefficient-by-coefficient-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-by-coefficient-interpretation">Coefficient-by-Coefficient Interpretation</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 64%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Interpretation</th>
<th>Stat. Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>0.0982</td>
<td>When all predictors are 0, the expected Bitcoin price is 0.0982 (not very interpretable in practice).</td>
<td>❌ Not significant</td>
</tr>
<tr class="even">
<td>Consumer Price Index</td>
<td>0.390</td>
<td>A 1-unit increase in CPI is associated with a 0.39 increase in Bitcoin price.</td>
<td>❌ Not significant (p = 0.719)</td>
</tr>
<tr class="odd">
<td>Federal Funds Rate</td>
<td>0.00227</td>
<td>Changes in the Fed Funds Rate have virtually no effect on Bitcoin price.</td>
<td>❌ Not significant (p = 0.917)</td>
</tr>
<tr class="even">
<td>U.S. Dollar Index</td>
<td>-0.783</td>
<td>A 1-unit increase in the dollar index (DXY) is associated with a 0.783 decrease in Bitcoin price.</td>
<td>✅ Significant (p = 0.0055)</td>
</tr>
<tr class="odd">
<td>M2 Money Supply</td>
<td>0.871</td>
<td>A 1-unit increase in the M2 money supply is associated with a 0.871 increase in Bitcoin price.</td>
<td>✅ Marginally significant (p = 0.049)</td>
</tr>
<tr class="even">
<td>Unemployment Rate</td>
<td>0.00469</td>
<td>No meaningful relationship between unemployment rate and Bitcoin price.</td>
<td>❌ Not significant (p = 0.913)</td>
</tr>
<tr class="odd">
<td>Gold Price</td>
<td>0.132</td>
<td>Weakly positive correlation with gold prices, but not strong or reliable.</td>
<td>❌ Not significant (p = 0.130)</td>
</tr>
<tr class="even">
<td>10 Year Treasury Yield</td>
<td>-0.0962</td>
<td>A 1-unit increase in 10-year Treasury yield predicts a 0.0962 decrease in Bitcoin price.</td>
<td>✅ Significant (p = 0.000195)</td>
</tr>
<tr class="odd">
<td>Dow Jones Index</td>
<td>1.01</td>
<td>A 1-unit increase in the Dow Jones Index is associated with a 1.01 increase in Bitcoin price.</td>
<td>✅ Very significant (p ≈ 0)</td>
</tr>
</tbody>
</table>
<p>✅ <strong>Most Important Predictors</strong></p>
<p><strong>Strongest Positive Influence</strong><br> Dow Jones Index (very strong correlation)<br> M2 Money Supply (positive monetary supply effect)<br></p>
<p><strong>Strongest Negative Influence</strong><br> U.S. Dollar Index (strong inverse relationship with the dollar index)<br> 10 Year Treasury Yield (higher yields hurt Bitcoin price)<br></p>
<p><strong>Insignificant Variables</strong><br> Consumer Price Index, Federal Funds Rate, Unemployment Rate, and Gold Price show no statistically significant effect in this model. That means their estimated impact on Bitcoin is uncertain or likely due to noise.</p>
</section>
</section>
<section id="granger-causality" class="level2">
<h2 class="anchored" data-anchor-id="granger-causality">Granger Causality</h2>
<p>To further investigate the directional relationships between Bitcoin price and key macroeconomic indicators, Granger causality analysis was conducted. This method is appropriate because it tests whether past values of one time series (e.g., interest rates, money supply, or inflation) can help predict future values of another time series (in this case, Bitcoin price), beyond what is explained by the past values of Bitcoin itself. Unlike simple correlation, which only captures contemporaneous association, Granger causality is particularly suited for time-series data where temporal ordering matters. It helps uncover potential lead-lag dynamics and predictive influence among variables.</p>
<p><strong>Bitcoin Price and Dow Jones Index</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: dow do not Granger-cause BTC

data:  VAR object var_model_btc_dow
F-Test = 0.51757, df1 = 5, df2 = 4042, p-value = 0.7632</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and 10 Year Treasury Yield</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: Treasury do not Granger-cause BTC

data:  VAR object var_model_btc_treasury
F-Test = 2.4423, df1 = 5, df2 = 4042, p-value = 0.03218</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and Gold Price</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: gold do not Granger-cause BTC

data:  VAR object var_model_btc_gold
F-Test = 1.1905, df1 = 5, df2 = 4042, p-value = 0.3111</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and Unemployment Rate</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: Unemployment do not Granger-cause BTC

data:  VAR object var_model_btc_unemployment
F-Test = 1.0096, df1 = 5, df2 = 4042, p-value = 0.4102</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and M2 Money Supply</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: M2 do not Granger-cause BTC

data:  VAR object var_model_btc_m2
F-Test = 1.8808, df1 = 5, df2 = 4042, p-value = 0.09425</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and U.S. Dollar Index</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: DXY do not Granger-cause BTC

data:  VAR object var_model_btc_dxy
F-Test = 2.0256, df1 = 5, df2 = 4042, p-value = 0.07193</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and Federal Funds Rate</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: FedRate do not Granger-cause BTC

data:  VAR object var_model_btc_fedrate
F-Test = 1.712, df1 = 5, df2 = 4042, p-value = 0.1282</code></pre>
</div>
</div>
<p><strong>Bitcoin Price and Consumer Price Index</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Granger causality H0: CPI do not Granger-cause BTC

data:  VAR object var_model_btc_cpi
F-Test = 0.90497, df1 = 5, df2 = 4042, p-value = 0.4767</code></pre>
</div>
</div>
<p>✅ <strong>Significant Granger Causality</strong></p>
<p><strong>10 Year Treasury Yield</strong><br> <em>p-value = 0.03218</em><br> Since the p-value is less than 0.05, we reject the null hypothesis.</p>
<p><strong>Interpretation:</strong> Past values of 10 Year Treasury Yield Granger-cause Bitcoin price. This suggests that interest rate movements (as captured by 10 Year Treasury Yield) have predictive power over Bitcoin prices.</p>
<p>⚠️ <strong>Marginal/Weak Evidence of Granger Causality</strong></p>
<p><strong>M2 Money Supply</strong><br> <em>p-value = 0.09425</em><br></p>
<p>Although the result is not statistically significant at the 5% level, it is close to the 10% threshold.</p>
<p><strong>Interpretation:</strong> There is some weak evidence that changes in money supply may help forecast Bitcoin price, but it’s not strong enough to draw firm conclusions.</p>
<p><strong>U.S. Dollar Index (DXY)</strong><br> <em>p-value = 0.07193</em><br> Similar to M2, the result is marginally significant at the 10% level, suggesting a potential predictive relationship.</p>
<p><strong>Interpretation:</strong> Dollar strength may have some predictive influence on Bitcoin, though the evidence is not strong at conventional significance levels.</p>
<p>❌ <strong>No Granger Causality Detected</strong></p>
<p><strong>Dow Jones Index</strong> (<em>p = 0.7632</em>)<br> <strong>Gold Price</strong> (<em>p = 0.3111</em>)<br> <strong>Unemployment Rate</strong> (<em>p = 0.4102</em>)<br> <strong>Federal Funds Rate</strong> (<em>p = 0.1282</em>)<br> <strong>Consumer Price Index (CPI)</strong> (<em>p = 0.4767</em>)<br></p>
<p>For all of these indicators, the p-values are well above 0.10, meaning we fail to reject the null hypothesis. Interpretation: There is no statistical evidence that these variables Granger-cause Bitcoin price. Their past values do not help predict Bitcoin movements in this model.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The analysis integrates insights from both a multiple linear regression model and Granger causality tests to assess the influence of various macroeconomic indicators on Bitcoin prices.</p>
<p>From the linear regression model, several predictors showed statistically significant relationships with Bitcoin price. Most notably, the Dow Jones Index exhibited a strong positive association (p &lt; 0.001), suggesting that increases in stock market performance correlate with higher Bitcoin prices. 10 Year Treasury Yield had a significant negative effect (p &lt; 0.001), indicating that higher interest rates may dampen Bitcoin demand, possibly due to rising opportunity costs. DXY (Dollar Index) also showed a significant negative effect (p = 0.005), implying that Bitcoin tends to decline as the U.S. dollar strengthens. Meanwhile, M2 money supply had a moderate positive effect (p ≈ 0.049), suggesting liquidity expansion may support Bitcoin valuation. Other variables like CPI, FedRate, Unemployment, and Gold did not exhibit statistically significant impacts in the regression model.</p>
<p>In contrast, the Granger causality analysis, which captures predictive relationships over time, revealed that 10 Year Treasury Yield Granger-cause Bitcoin price (p = 0.032), confirming their temporal influence. M2 money supply (p = 0.094) and DXY (p = 0.072) provided weak evidence of predictive power at the 10% significance level, but other indicators including the Dow Jones, despite its strong regression coefficient, did not Granger-cause Bitcoin price. This implies that while these factors may co-move with Bitcoin (as seen in regression), they do not necessarily have predictive power over Bitcoin’s future movements.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/skawakamNY\.github\.io\/bitcoin_analysis\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>